# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Cody Kauhl
email: your-email@domain.com
author: Cody Kauhl
description: Digital Media Artist
copyright: '&copy; 2019 Cody Kauhl. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://twitter.com/codykauhl
  - title: github
    url: https://github.com/codykauhl
  - title: linkedin
    url: https://www.linkedin.com/in/codykauhl/
